<?php
// Prepare the item set queries
$ids = isset($query['item_set_id']) ? $query['item_set_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
?>
<div id="item-sets" class="field removable multi-value" role="group" aria-labelledby="by-item-set-label">
    <fieldset>
<!--	<div class="field-meta"> -->
        <legend id="by-item-set-label"><?php echo $this->translate('Search by item set'); ?></legend>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $this->translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description help-block"><?php echo $this->translate('Searches for items that are assigned to any of these item sets.'); ?></div>
        </div>
   <!-- </div>-->
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => ['value' => $id],
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button btn btn-primary"><i class="fa fa-trash" aria-hidden="true" title="Remove Value"></i><span class="sr-only"><?php echo $this->translate('Remove value'); ?></span></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> <?php echo $this->translate('Add new item set'); ?></a>
    </div>
    </fieldset>
</div>
