<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<div class="row">
	<div class="col-sm-3">
		<span id="type-title"><?php echo $this->translate('Media'); ?></span>
	</div>
	<div class="col-sm-9" id="page-title">
		<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
	</div>
</div>
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->render(); ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>
